### ISSUE TITLE
Refactor module name

### ISSUE THREAD

**Issue by urko-b** [robertt3kuk/go-sherlock#1]
Hi, I've seen module name is not following the convention of: `github.com/username/repo-name` https://github.com/robertt3kuk/go-sherlock/blob/47857e807bba437a24a59d2fb4f5666915a4102a/go.mod#L1

I can fix this through PR

**Comment by robertt3kuk** [comment]
I will be pleased

**Comment by urko-b** [comment]
#3 relates to
